name: Weekly Dependency Updates

on:
  push:
    branches: [ main, master ]
  schedule:
    # Run every Sunday at 10:00 AM UTC
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        update-type: [patch, minor]

    outputs:
      create_deprecated_issue: ${{ steps.set_deprecated_issue_flag.outputs.create_deprecated_issue }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g npm-check-updates

      - name: Check for outdated packages
        id: outdated
        run: |
          echo "Checking for outdated packages..."
          # Save JSON to file to avoid output formatting issues
          npm outdated --json 2>/dev/null > outdated.json || echo '{}' > outdated.json
          
          # Check if there are any outdated packages
          OUTDATED_COUNT=$(cat outdated.json | jq 'length' 2>/dev/null || echo '0')
          if [ "$OUTDATED_COUNT" -eq 0 ]; then
            echo "has_updates=false" >> $GITHUB_OUTPUT
            echo "No outdated packages found"
          else
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "Found $OUTDATED_COUNT outdated packages"
          fi

      - name: Security audit
        id: audit
        run: |
          echo "Running security audit..."
          # Save audit result to file
          npm audit --audit-level moderate --json 2>/dev/null > audit_result.json || echo '{"vulnerabilities":{}}' > audit_result.json

          # Check for high/critical vulnerabilities safely
          HIGH_VULNS=$(cat audit_result.json | jq '.metadata.vulnerabilities.high // 0' 2>/dev/null || echo '0')
          CRITICAL_VULNS=$(cat audit_result.json | jq '.metadata.vulnerabilities.critical // 0' 2>/dev/null || echo '0')

          if [ "$HIGH_VULNS" -gt 0 ] || [ "$CRITICAL_VULNS" -gt 0 ]; then
            echo "has_security_issues=true" >> $GITHUB_OUTPUT
            echo "Found $HIGH_VULNS high and $CRITICAL_VULNS critical vulnerabilities"
          else
            echo "has_security_issues=false" >> $GITHUB_OUTPUT
            echo "No critical security vulnerabilities found"
          fi

      - name: Update dependencies (patch level)
        if: matrix.update-type == 'patch' && steps.outdated.outputs.has_updates == 'true'
        run: |
          echo "Updating patch-level dependencies..."
          ncu --target patch --upgrade
          npm install

      - name: Update dependencies (minor level)
        if: matrix.update-type == 'minor' && steps.outdated.outputs.has_updates == 'true'
        run: |
          echo "Updating minor-level dependencies..."
          ncu --target minor --upgrade
          npm install

      - name: Run tests and build
        if: steps.outdated.outputs.has_updates == 'true'
        run: |
          echo "Running linting..."
          npm run lint || echo "Linting not available or failed"

          echo "Running build..."
          npm run build || echo "Build not available or failed"

      - name: Generate update summary
        if: steps.outdated.outputs.has_updates == 'true'
        id: summary
        run: |
          echo "Generating update summary..."

          # Check if files were changed
          if git diff --quiet package.json package-lock.json; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in package files"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in package files"
            
            # Create update summary
            echo "## Dependency Updates Summary" > update_summary.md
            echo "" >> update_summary.md
            echo "### Update Type: ${{ matrix.update-type }}" >> update_summary.md
            echo "" >> update_summary.md

            # Get updated packages (compare with index instead of HEAD~1)
            if [ -f "package.json" ]; then
              echo "### Updated Packages:" >> update_summary.md
              echo '```diff' >> update_summary.md
              git diff --no-index /dev/null package.json | grep "^+" | grep -E '"\s*:\s*"[^"]*"' | head -10 >> update_summary.md || echo "Package changes detected" >> update_summary.md
              echo '```' >> update_summary.md
              echo "" >> update_summary.md
            fi

            # Security info
            if [ "${{ steps.audit.outputs.has_security_issues }}" = "true" ]; then
              echo "### Security Issues Detected" >> update_summary.md
              echo "Please review the security audit results." >> update_summary.md
              echo "" >> update_summary.md
            else
              echo "### No Security Issues Detected" >> update_summary.md
              echo "" >> update_summary.md
            fi

            echo "### Test Results:" >> update_summary.md
            echo "- Linting: Completed" >> update_summary.md
            echo "- Build: Completed" >> update_summary.md
            echo "" >> update_summary.md

            echo "### Useful Links:" >> update_summary.md
            echo "- [NPM Changelog](https://github.com/npm/cli/releases)" >> update_summary.md
            echo "- [Node.js Releases](https://nodejs.org/en/about/releases/)" >> update_summary.md
            echo "" >> update_summary.md

            # Use proper multiline output format
            {
              echo "summary_content<<EOF"
              cat update_summary.md
              echo "EOF"
            } >> $GITHUB_OUTPUT
          fi

      - name: Check for breaking changes
        if: steps.summary.outputs.has_changes == 'true'
        id: breaking_changes
        run: |
          echo "Checking for potential breaking changes..."

          # List of packages that might introduce breaking changes
          CRITICAL_PACKAGES=("next" "react" "react-dom" "@types/react" "@types/react-dom" "typescript" "tailwindcss")

          HAS_CRITICAL_UPDATES=false
          CRITICAL_UPDATES=""

          for package in "${CRITICAL_PACKAGES[@]}"; do
            if git diff package.json | grep -q "\"$package\""; then
              HAS_CRITICAL_UPDATES=true
              CRITICAL_UPDATES="${CRITICAL_UPDATES}- $package\n"
            fi
          done

          if [ "$HAS_CRITICAL_UPDATES" = true ]; then
            echo "has_breaking_changes=true" >> $GITHUB_OUTPUT
            echo "critical_packages<<EOF" >> $GITHUB_OUTPUT
            echo -e "$CRITICAL_UPDATES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_breaking_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Deprecated package check
        if: steps.summary.outputs.has_changes == 'true'
        id: deprecated
        run: |
          echo "Checking for deprecated packages..."

          # Check for deprecated packages safely
          DEPRECATED_CHECK=$(npm ls --depth=0 --json 2>/dev/null | jq -r '.dependencies | to_entries[]? | select(.value.deprecated?) | .key' 2>/dev/null || echo "")

          if [ -n "$DEPRECATED_CHECK" ] && [ "$DEPRECATED_CHECK" != "" ]; then
            echo "has_deprecated=true" >> $GITHUB_OUTPUT
            echo "deprecated_packages<<EOF" >> $GITHUB_OUTPUT
            echo "$DEPRECATED_CHECK" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_deprecated=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip update if deprecated packages found
        if: steps.deprecated.outputs.has_deprecated == 'true'
        id: set_deprecated_issue_flag
        run: |
          echo "Deprecated packages detected:"
          echo "${{ steps.deprecated.outputs.deprecated_packages }}"
          echo "Skipping this update to prevent issues."

          # Create issue content
          cat > deprecated_issue.md << 'EOF'
          ## Deprecated Dependencies Detected

          The following packages in our project are deprecated and need attention:

          ${{ steps.deprecated.outputs.deprecated_packages }}

          ### Action Required:
          1. Review each deprecated package
          2. Find suitable alternatives
          3. Update code to use new packages
          4. Test thoroughly before merging

          ### Resources:
          - [NPM Package Health](https://snyk.io/advisor/)
          - [Package Alternatives](https://www.npmtrends.com/)

          **Note:** Automated dependency updates have been paused until this is resolved.
          EOF

          echo "create_deprecated_issue=true" >> $GITHUB_OUTPUT
          exit 1

      - name: Skip update if critical security issues
        if: steps.audit.outputs.has_security_issues == 'true' && steps.breaking_changes.outputs.has_breaking_changes == 'true'
        run: |
          echo "Critical security issues detected with potential breaking changes."
          echo "Manual review required before proceeding with update."
          exit 1

      - name: Create Pull Request
        if: steps.summary.outputs.has_changes == 'true' && steps.deprecated.outputs.has_deprecated == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(${{ matrix.update-type }}): update dependencies

            - Updated ${{ matrix.update-type }}-level dependencies
            - All tests and builds passing
            - No security vulnerabilities detected
          title: 'Weekly Dependency Updates (${{ matrix.update-type }})'
          body: |
            ${{ steps.summary.outputs.summary_content }}

            ${{ steps.breaking_changes.outputs.has_breaking_changes == 'true' && format('### Potential Breaking Changes{0}The following critical packages were updated:{0}{1}{0}{0}**Please review carefully before merging!**{0}', '\n', steps.breaking_changes.outputs.critical_packages) || '' }}

            ---

            This PR was automatically created by the weekly dependency update workflow.

            ### Checklist:
            - [x] Dependencies updated
            - [x] Build completed  
            - [x] Linting completed
            - [x] No deprecated packages
            ${{ steps.audit.outputs.has_security_issues == 'false' && '- [x] No security vulnerabilities' || '- [ ] Security audit needs review' }}

            ### Review Instructions:
            1. Check the updated packages
            2. Test the application locally
            3. Verify all features work as expected
            4. Merge if everything looks good

          branch: automated-dependency-updates-${{ matrix.update-type }}
          delete-branch: true
          labels: |
            dependencies
            automated
            ${{ matrix.update-type }}-update

      - name: Clean up
        if: always()
        run: |
          rm -f outdated.json audit_result.json update_summary.md deprecated_issue.md

  create-deprecated-issue:
    needs: update-dependencies
    runs-on: ubuntu-latest
    if: needs.update-dependencies.outputs.create_deprecated_issue == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create deprecated packages content
        run: |
          cat > deprecated_issue.md << 'EOF'
          ## Deprecated Dependencies Need Attention

          Some dependencies in this project are deprecated and need manual review.

          ### Action Required:
          1. Review deprecated packages
          2. Find suitable alternatives
          3. Update code to use new packages
          4. Test thoroughly before merging

          ### Resources:
          - [NPM Package Health](https://snyk.io/advisor/)
          - [Package Alternatives](https://www.npmtrends.com/)

          **Note:** Automated dependency updates have been paused until this is resolved.
          EOF

      - name: Create issue for deprecated packages
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: create deprecated packages issue'
          title: 'Deprecated Dependencies Need Attention'
          body-path: deprecated_issue.md
          branch: deprecated-packages-issue
          labels: |
            dependencies
            deprecated
            high-priority

  notify-completion:
    needs: [update-dependencies, create-deprecated-issue]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Workflow Summary
        run: |
          echo "## Weekly Dependency Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ needs.update-dependencies.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.update-dependencies.result }}" = "success" ]; then
            echo "Dependencies successfully updated!" >> $GITHUB_STEP_SUMMARY
            echo "Check for new pull requests in this repository." >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.update-dependencies.result }}" = "failure" ]; then
            echo "Dependency update failed." >> $GITHUB_STEP_SUMMARY
            echo "This might be due to:" >> $GITHUB_STEP_SUMMARY
            echo "- Deprecated packages detected" >> $GITHUB_STEP_SUMMARY
            echo "- Critical security issues with breaking changes" >> $GITHUB_STEP_SUMMARY
            echo "- Build or test failures" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the logs and address any issues manually." >> $GITHUB_STEP_SUMMARY
          else
            echo "No updates were needed." >> $GITHUB_STEP_SUMMARY
          fi
